# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd

name: iotdevice-marvell-espressobin-kernel
summary: EspressoBin kernel for snappy
description: This is an EspressoBin snapped kernel

build-base: core20
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on:
      - amd64
      - arm64
    run-on: arm64

package-repositories:
  - type: apt
    url: http://ports.ubuntu.com
    architectures: [arm64]
    components: [main]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    key-server: keyserver.ubuntu.com
    suites:
      - focal
      - focal-updates
      - focal-security
      - focal-backports

parts:
  kernel:
    plugin: nil
    stage-packages:
      - linux-image-generic-hwe-20.04
    organize:
      lib/firmware/*/device-tree/marvell/armada-3720-espressobin.dtb: dtbs/
      lib/modules: modules
      boot/vmlinuz-*: kernel.img
    override-build: |
      snapcraftctl build
      snapcraftctl set-version $(basename ${SNAPCRAFT_PART_INSTALL}/boot/config-* | cut -d- -f2-)
      snapcraftctl set-grade stable
    stage:
      - modules
      - dtbs
      - kernel.img

  initrd:
    plugin: x_initrd
    stage-packages:
      - linux-image-generic-hwe-20.04
      - linux-headers-generic-hwe-20.04
    kernel-initrd-channel: beta
    kernel-initrd-configured-modules:
      - sdhci-xenon-driver
      - gpio-regulator
      - nls_iso8859-1
    kernel-image-target: vmlinuz

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    # Remove large firmware files that will never be needed
    prime:
      - -usr
      - -firmware/netronome
      - -firmware/intel
      - -firmware/amdgpu
      - -firmware/liquidio
      - -firmware/qcom
      - -firmware/mellanox
      - -firmware/radeon
      - -firmware/i915
      - -firmware/brcm
      - -firmware/qek
      - -firmware/ath10k
    organize:
      lib/firmware: firmware
