# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: qti-sa8155p-kernel
summary: Snapdragon kernel for snappy
description: This is a snapdragon snapped kernel, based off msm kernel.lnx.4.14.r18-rel

grade: stable
build-base: core18
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

parts:
  kernel:
    after:
      - libufdt
      - firmware-custom
    plugin: kernel
    source: https://git.launchpad.net/~ubuntu-cervinia/+git/linux-kernel
    source-type: git
    source-depth: 1
    source-branch: master
    kconfigflavour: "qcomm"
    kernel-with-firmware: false
    kernel-image-target: Image-dtb
    kernel-compiler-parameters:
      - CC=clang
      - DTC_EXT=dtc
    kernel-initrd-core-base: core20
    kernel-initrd-flavour: edge
    kernel-initrd-compression: gz
    kernel-initrd-firmware:
      - firmware/venus.*
    override-build: |
      snapcraftctl build
      mkdir -p  ${SNAPCRAFT_PART_INSTALL}/dtbs/
      cp ${SNAPCRAFT_PART_BUILD}/arch/arm64/boot/dts/qcom/*.dtb \
         ${SNAPCRAFT_PART_INSTALL}/dtbs
      kernel_version="$(git describe --tags  | cut -c 14-)"
      # build dtbo image if there are any dtbo files
      if ls ${SNAPCRAFT_PART_BUILD}/arch/arm64/boot/dts/qcom/*.dtbo 1> /dev/null 2>&1; then
          ${SNAPCRAFT_STAGE}/mkdtboimg.py create \
                             ${SNAPCRAFT_PART_INSTALL}/dtbo.img \
                             ${SNAPCRAFT_PART_BUILD}/arch/arm64/boot/dts/qcom/*.dtbo
          kernel_version="${kernel_version}-dtbo"
      fi
      snapcraftctl set-version ${kernel_version}
    stage:
      - System.map-*
      - config-*
      - dtb*
      - initrd.img
      - kernel.img
      - modules
      - -modules/*/build
      - -modules/*/source
    prime:
      - -initrd.img
      - -kernel.img
      - -dtbs

  firmware-custom:
    plugin: dump
    source: .
    source-type: local
    override-pull: |
      # allow custom source definition
      if [ -n "${SNAPDRAGON_KERNEL_SNAP_FIRMWARE:-}" ]; then
        if [ -d ${SNAPDRAGON_KERNEL_SNAP_FIRMWARE} ]; then
          cp -r ${SNAPDRAGON_KERNEL_SNAP_FIRMWARE}/* ${SNAPCRAFT_PART_SRC}
        else
          git clone --depth 1 ${SNAPDRAGON_KERNEL_SNAP_FIRMWARE} ${SNAPCRAFT_PART_SRC}
        fi
      else
        echo "Missing env SNAPDRAGON_KERNEL_SNAP_FIRMWARE no custom firmware will be included"
      fi
    organize:
      '*': firmware/

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
    override-build: |
      snapcraftctl build
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/firmware/wlan \
               ${SNAPCRAFT_PART_INSTALL}/firmware/smsc75xx \
               ${SNAPCRAFT_PART_INSTALL}/lib
      ln -s ../firmware ${SNAPCRAFT_PART_INSTALL}/lib/firmware
    stage:
      - -firmware/amd
      - -firmware/amdgpu
      - -firmware/asihpi
      - -firmware/cavium
      - -firmware/cxgb3
      - -firmware/cxgb4
      - -firmware/dpaa2
      - -firmware/i915
      - -firmware/imx
      - -firmware/intel
      - -firmware/iwlwifi-*
      - -firmware/liquidio
      - -firmware/matrox
      - -firmware/mellanox
      - -firmware/mrvl
      - -firmware/netronome
      - -firmware/nvidia
      - -firmware/qed
      - -firmware/radeon
      - -firmware/rockchip
      - -firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
      - -firmware/ath3k-1.fw
      - -firmware/qca/htbtfw20.tlv
      - -firmware/qcom/sdm845
      - -firmware/qcom/venus*
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib

  libufdt:
    plugin: dump
    source: https://android.googlesource.com/platform/system/libufdt
    source-type: git
    source-branch: master
    organize:
      utils/src/mkdtboimg.py: mkdtboimg.py
    stage:
      - mkdtboimg.py
    prime:
      - -*

build-packages:
  - dpkg-dev
  - android-tools-mkbootimg
  - libssl-dev
  - libfdt-dev
  - cpio
  - clang
  - binutils-aarch64-linux-gnu
  - on amd64:
    - gcc-aarch64-linux-gnu
  - else:
    - gcc
