# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: qti-sa8155p-kernel
summary: Snapdragon kernel for snappy
description: This is a snapdragon snapped kernel, based off msm kernel.lnx.4.14.r18-rel

grade: stable
build-base: core18
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

parts:
  firmware-custom:
    plugin: dump
    source: .
    source-type: local
    override-pull: |
      # allow custom source definition
      if [ -n "${SNAPDRAGON_KERNEL_SNAP_FIRMWARE:-}" ]; then
        if [ -d ${SNAPDRAGON_KERNEL_SNAP_FIRMWARE} ]; then
          cp -r ${SNAPDRAGON_KERNEL_SNAP_FIRMWARE}/* ${SNAPCRAFT_PART_SRC}
        else
          git clone --depth 1 ${SNAPDRAGON_KERNEL_SNAP_FIRMWARE} ${SNAPCRAFT_PART_SRC}
        fi
      else
        echo "Missing env SNAPDRAGON_KERNEL_SNAP_FIRMWARE no custom firmware will be included"
      fi
    organize:
      '*': firmware/

  libufdt:
    plugin: dump
    source: https://android.googlesource.com/platform/system/libufdt
    source-type: git
    source-branch: master
    organize:
      utils/src/mkdtboimg.py: mkdtboimg.py
    stage:
      - mkdtboimg.py
    prime:
      - -*

build-packages:
  - dpkg-dev
  - android-tools-mkbootimg
  - libssl-dev
  - libfdt-dev
  - cpio
  - clang
  - binutils-aarch64-linux-gnu
  - on amd64:
    - gcc-aarch64-linux-gnu
  - else:
    - gcc
