# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd

name: espressobin-kernel
summary: EspressoBin kernel for snappy
description: This is an EspressoBin snapped kernel

grade: stable
build-base: core20
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: 
      - amd64   
      - arm64
    run-on: arm64

parts:
  kernel:
    plugin: x-kernel
    source: git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/focal
    source-type: git
    source-depth: 1
    source-branch: hwe-5.13 
    kernel-with-firmware: false
    kernel-image-target: Image
    kernel-device-trees: 
      - marvell/armada-3720-espressobin
    kernel-initrd-channel: stable
    kernel-initrd-compression: gz
    kconfigflavour: generic
    kconfigs:
      - CONFIG_SYSTEM_REVOCATION_KEYS=""
      - CONFIG_SYSTEM_TRUSTED_KEYS=""
    override-pull: |
      snapcraftctl pull
      touch ${SNAPCRAFT_PART_SRC}/debian.hwe-5.13/config/config.common.ports
    override-build: |
      snapcraftctl build
      snapcraftctl set-version $(dpkg-parsechangelog -l ${SNAPCRAFT_PART_SRC}/debian.hwe-5.13/changelog -S version)
    stage:
      - System.map-*
      - config-*
      - initrd.img
      - kernel.img
      - modules
      - dtbs/*
      - -modules/*/build
      - -modules/*/source 
  firmware:
    plugin: nil
    source: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
    source-type: git
    source-branch: main
    source-depth: 1
    override-build: |
      mkdir ${SNAPCRAFT_PART_INSTALL}/firmware
      cp -r ${SNAPCRAFT_PART_SRC}/* ${SNAPCRAFT_PART_INSTALL}/firmware/

build-packages:
  - dpkg-dev
  - android-tools-mkbootimg
  - libssl-dev
  - libfdt-dev
  - cpio
  - binutils-aarch64-linux-gnu
  - device-tree-compiler
  - libelf-dev
  - on amd64:
    - gcc-aarch64-linux-gnu
  - else:
    - gcc
