# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: espressobin-kernel
summary: EspressoBin kernel for snappy
description: This is an EspressoBin snapped kernel

grade: stable
build-base: core20
confinement: devmode
type: kernel
adopt-info: kernel

architectures:
  - build-on: 
      - amd64   
      - arm64
    run-on: arm64

# environment to run fde-setup hook
environment:
    SNAP_TA_PATH:    /lib/firmware
    LD_LIBRARY_PATH: ${SNAP_LIBRARY_PATH}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}

parts:
  kernel:
    plugin: x-kernel
    source: git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy 
    source-type: git
    source-branch: master-next
    kernel-with-firmware: false
    kernel-image-target: Image
    kernel-device-trees: 
      - marvell/armada-3720-espressobin
    kernel-compiler-parameters:
      - DTC_EXT=dtc
    kernel-initrd-channel: stable
    kernel-initrd-compression: gz
    override-build: |
      echo CONFIG_SQUASHFS_XZ=y >> ${SNAPCRAFT_PART_SRC}/arch/arm64/configs/defconfig
      snapcraftctl build
      kernel_version="$(git --git-dir=${SNAPCRAFT_PART_SRC}/.git describe --tags  | cut -c 8-)"
      snapcraftctl set-version ${kernel_version}
    stage:
      - System.map-*
      - config-*
      - initrd.img
      - kernel.img
      - modules
      - dtbs/*
      - -modules/*/build
      - -modules/*/source 
  firmware:
    plugin: nil
    source: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
    source-type: git
    source-branch: main
    source-depth: 1
    override-build: |
      mkdir ${SNAPCRAFT_PART_INSTALL}/firmware
      cp -r ${SNAPCRAFT_PART_SRC}/* ${SNAPCRAFT_PART_INSTALL}/firmware/

build-packages:
  - dpkg-dev
  - android-tools-mkbootimg
  - libssl-dev
  - libfdt-dev
  - cpio
  - binutils-aarch64-linux-gnu
  - device-tree-compiler
  - on amd64:
    - gcc-aarch64-linux-gnu
  - else:
    - gcc
