# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd

name: iotdevice-marvell-espressobin-kernel
summary: EspressoBin kernel
description: This is an EspressoBin snapped kernel

grade: stable
build-base: core20
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  # Cross-compiling on amd64 is currently broken
  - build-on: arm64

package-repositories:
  - type: apt
    architectures:
      - arm64
    components:
      - main
    suites:
      - focal
      - focal-updates
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports/

parts:
  kernel:
    plugin: x_initrd
    stage-packages:
      - linux-generic-hwe-20.04
      - linux-headers-generic-hwe-20.04
    kernel-initrd-modules:
      # Required for loading the SD-Card
      - sdhci-xenon-driver
      - gpio-regulator
      # Required for network access
      - mv88e6xxx
      - mvneta
      - mvmdio
    kernel-initrd-channel: stable
    kernel-initrd-compression: gz
    kernel-image-target: vmlinuz
    override-build: |
      mkdir ${SNAPCRAFT_PART_INSTALL}/dtbs
      cp ${SNAPCRAFT_PART_INSTALL}/lib/firmware/*/device-tree/marvell/armada-3720-espressobin.dtb ${SNAPCRAFT_PART_INSTALL}/dtbs/
      snapcraftctl build
      KVER=$(ls ${SNAPCRAFT_PART_INSTALL}/modules/)
      snapcraftctl set-version ${KVER}
    stage:
      - System.map-*
      - config-*
      - dtbs/
      - modules/
      - kernel.img
      - initrd.img
      - -boot
      - -usr
      - -etc
      - -sbin
      - -lib
