name: Snapcraft

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Git submodules
        run: git submodule update --init --recursive

      - name: Snap fetch
        run: sudo snap install --classic snapcraft

      - name: Snapcraft
        run: snapcraft --destructive-mode --target-arch=arm64 --enable-experimental-target-arch
